# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clinvk < Formula
  desc "Unified AI CLI wrapper for multiple backends"
  homepage "https://github.com/signalridge/clinvoker"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.3.0/clinvoker_0.3.0_darwin_amd64.tar.gz"
      sha256 "70c1dfad9642a72a9949a3c71510fe511a73fdbe11aaef53804480132eb45512"

      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.3.0/clinvoker_0.3.0_darwin_arm64.tar.gz"
      sha256 "d0216394d9738a4191cc252cee9a0d568ff25b42f0ebbabf8193b676eb7d786c"

      def install
        bin.install "clinvk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.3.0/clinvoker_0.3.0_linux_amd64.tar.gz"
      sha256 "a863451473f03e454a2d19427337909c5e32199f362fe741080e61329643017a"
      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.3.0/clinvoker_0.3.0_linux_arm64.tar.gz"
      sha256 "d13a3a1390f19ec32d023b62412d0528e1fa81ccf8123817681087a77b23aafb"
      def install
        bin.install "clinvk"
      end
    end
  end

  test do
    system "#{bin}/clinvk", "--version"
  end
end
