# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clinvk < Formula
  desc "Unified AI CLI wrapper for multiple backends"
  homepage "https://github.com/signalridge/clinvoker"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.2.0/clinvoker_0.2.0_darwin_amd64.tar.gz"
      sha256 "381acafed056d75896b5b1d411d819fc3549c90e4f0f381f431faf6fbde6a023"

      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.2.0/clinvoker_0.2.0_darwin_arm64.tar.gz"
      sha256 "276f008f66b3214ad1589898565e36620750a7668879ffb6a6136c7a4660fc2a"

      def install
        bin.install "clinvk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.2.0/clinvoker_0.2.0_linux_amd64.tar.gz"
      sha256 "8ba29267e08f7cd0731378d2852f9ca1fefe9a88646ba6f04bbdeb500e64e7fa"
      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.2.0/clinvoker_0.2.0_linux_arm64.tar.gz"
      sha256 "d6bd7da9caf2a6808f477004bf1e4499ca4d1039b861c71975b1e7df60fa1235"
      def install
        bin.install "clinvk"
      end
    end
  end

  test do
    system "#{bin}/clinvk", "--version"
  end
end
