# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clinvk < Formula
  desc "Unified AI CLI wrapper for multiple backends"
  homepage "https://github.com/signalridge/clinvoker"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.4.0/clinvoker_0.4.0_darwin_amd64.tar.gz"
      sha256 "9f8887877c60cfc9ed48fbd2b5336d97a28b6ec73ca6d0d2f60ca8890ac0327c"

      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.4.0/clinvoker_0.4.0_darwin_arm64.tar.gz"
      sha256 "c934a47be227bafb35192ca41cdfac88594e91c55e4b1b4722889d718605d384"

      def install
        bin.install "clinvk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.4.0/clinvoker_0.4.0_linux_amd64.tar.gz"
      sha256 "652fed4600d58683afa9d8a3f64f71dbcc8745496d9751656665873ab22848cb"
      def install
        bin.install "clinvk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signalridge/clinvoker/releases/download/v0.4.0/clinvoker_0.4.0_linux_arm64.tar.gz"
      sha256 "13edc38375313ff2569872672dc6c5b8bb6b9cc884c05fbf2be9be83daa8577c"
      def install
        bin.install "clinvk"
      end
    end
  end

  test do
    system "#{bin}/clinvk", "--version"
  end
end
