# This file was generated by GoReleaser. DO NOT EDIT.
cask "slipway" do
  version "0.32.1"

  on_macos do
    on_intel do
      sha256 "e97f70ddf71b8bc04903dbeaf05c90e27445274c8efff9950ff7d4c2f78c47a2"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "0d9c424007e254c9c856c2ca1a3a3dc9dcd30ad82257efcf0c3f92f093332edb"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  on_linux do
    on_intel do
      sha256 "07c0cca40d584a3e72a2c439bead74afdf4e11ea519b9945aa4aee3321d818eb"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "6fe42a9167e80fb318fa6bb7b05021027f8011d39f10cf5a7966b32dcc85d98d"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  name "slipway"
  desc "Governance CLI for AI-assisted software delivery"
  homepage "https://github.com/signalridge/slipway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slipway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slipway"]
    end
  end

  # No zap stanza required

end
