# This file was generated by GoReleaser. DO NOT EDIT.
cask "slipway" do
  version "0.40.0"

  on_macos do
    on_intel do
      sha256 "b53190a016d2d87dbdcf102d7ecac680f5341c122a8a0f9d275d2619808e32cb"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "019525f86c0a6ff64a7a2d8d15cab48e8fc5487b45813a208244801786f673bb"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae046e77b894db51bd415741d173b4afbabc3bfc26f677fa89a29af2d5d7835f"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "09d3c7741f412123be32f221e5fa2ba0c9d8ac4ebfa0890e573cb3c522b9b69b"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  name "slipway"
  desc "Governance CLI for AI-assisted software delivery"
  homepage "https://github.com/signalridge/slipway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slipway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slipway"]
    end
  end

  # No zap stanza required

end
