# This file was generated by GoReleaser. DO NOT EDIT.
cask "slipway" do
  version "0.25.1"

  on_macos do
    on_intel do
      sha256 "7176becedc2264e2375d18d3d6b19d907a6fe59d03670ce1d4cca4ec1296b12a"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "78041ead776216bb7caeb2df57dba5a4a686198e117559f876f635cba596f290"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b96f8445f26fc91c93f66e9b5c158f80c5567d9c7b2546adf6a74180a5fce8c5"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_amd64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
    on_arm do
      sha256 "3fae648ecc0b0146be0e871ee810a1745350bc588f26e43a2c75044f6b8c2952"
      url "https://github.com/signalridge/slipway/releases/download/v#{version}/slipway_#{version}_linux_arm64.tar.gz",
        verified: "github.com/signalridge/slipway/"
    end
  end

  name "slipway"
  desc "Governance CLI for AI-assisted software delivery"
  homepage "https://github.com/signalridge/slipway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slipway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slipway"]
    end
  end

  # No zap stanza required

end
